export const REFERRAL_SOURCE_OPTIONS = [
  { value: "instituto_premierpet", label: "Instituto PremieRpet" },
  { value: "cobasi", label: "Cobasi" },
  { value: "abra", label: "ABRA – Associação Brasileira de Reciclagem Animal" },
  { value: "redes_sociais_mv", label: "Redes sociais do MV Abrigos Brasil" },
  { value: "redes_sociais_parceiros", label: "Redes sociais de parceiros" },
  { value: "google", label: "Pesquisa no Google / Internet" },
  { value: "site_institucional", label: "Site institucional do MV Abrigos Brasil" },
  { value: "indicacao_abrigo", label: "Indicação de outro abrigo" },
  { value: "indicacao_protetor", label: "Indicação de protetor(a) independente" },
  { value: "indicacao_veterinario", label: "Indicação de médico(a)-veterinário(a) ou clínica veterinária" },
  { value: "indicacao_ong", label: "Indicação de ONG ou instituição de proteção animal" },
  { value: "evento", label: "Evento, curso, palestra ou capacitação" },
  { value: "imprensa", label: "Imprensa (reportagem, entrevista, matéria)" },
  { value: "orgao_publico", label: "Órgão público (prefeitura, secretaria, conselho, etc.)" },
  { value: "outro", label: "Outro" },
];
